# Generated by Django 5.2.7 on 2026-09-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Intitulé du programme')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('instrument', models.CharField(max_length=100, verbose_name='Discipline')),
                ('category', models.CharField(max_length=80, verbose_name='Catégorie (Claviers, Cordes, Rythme, etc.)')),
                ('aca_certification', models.CharField(default='Diplôme Certifié ACA - Grades 1 à 8', max_length=200, verbose_name='Certification American Canadian Academy correspondante')),
                ('summary', models.CharField(max_length=300, verbose_name='Résumé accrocheur')),
                ('description', models.TextField(verbose_name='Présentation détaillée')),
                ('formats_available', models.CharField(default='Cours individuels & Ateliers de groupe disponibles', max_length=150, verbose_name='Formats dispensés')),
                ('syllabus', models.TextField(blank=True, verbose_name='Contenu pédagogique & pièces au programme')),
                ('recommended_age', models.CharField(default='Dès 6 ans & adultes', max_length=80, verbose_name='Âge conseillé')),
                ('weekly_hours', models.CharField(default='1 à 2 séances / semaine', max_length=80, verbose_name='Volume horaire')),
                ('monthly_fee', models.CharField(default='6 500 DA - 10 000 DA / mois', max_length=80, verbose_name='Tarif indicatif')),
                ('icon_name', models.CharField(default='Music', max_length=50, verbose_name="Nom de l'icône Lucide")),
                ('badge', models.CharField(blank=True, default='Accrédité ACA', max_length=80, verbose_name='Badge visuel')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': "Programme d'enseignement",
                'verbose_name_plural': "Programmes d'enseignement",
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(blank=True, editable=False, max_length=32, unique=True, verbose_name="Matricule d'inscription")),
                ('first_name', models.CharField(max_length=100, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=100, verbose_name='Nom de famille')),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('phone', models.CharField(max_length=25, verbose_name='Numéro de téléphone')),
                ('commune', models.CharField(default='Alger', max_length=100, verbose_name='Commune de résidence (ex: Hydra, Didouche, Kouba, El Biar...)')),
                ('instrument', models.CharField(choices=[('piano', 'Piano (Classique, Jazz & Moderne)'), ('violon', 'Violon & Cordes'), ('guitare', 'Guitare (Classique, Acoustique, Électrique)'), ('batterie', 'Batterie & Percussions'), ('chant', 'Chant & Technique Vocale'), ('violoncelle', 'Violoncelle'), ('oud', 'Luth Arabe / Oud & Musique Andalouse'), ('eveil', 'Éveil Musical (4 - 7 ans)'), ('solfege', 'Formation Musicale & Solfège')], default='piano', max_length=50, verbose_name='Instrument souhaité')),
                ('lesson_format', models.CharField(choices=[('individuel', 'Cours Individuel (Suivi personnalisé sur mesure)'), ('groupe', "Cours en Groupe (Atelier d'ensemble & émulation collective)"), ('hybride', 'Formule Duo / Hybride (Individuel + Atelier collectif)')], default='individuel', max_length=30, verbose_name='Format des cours (Individuel ou Groupe)')),
                ('curriculum_type', models.CharField(choices=[('aca_certified', 'Cursus International American Canadian Academy (Examens & Certifications)'), ('leisure', 'Cursus Découverte & Pratique Libre'), ('conservatoire', 'Cursus Académique Supérieur & Préparation Concours')], default='aca_certified', max_length=50, verbose_name='Filière choisie')),
                ('formula', models.CharField(choices=[('1_seance', 'Formule 1 séance par semaine (6 500 DZD / mois)'), ('2_seances', 'Formule 2 séances par semaine (10 000 DZD / mois)')], default='2_seances', max_length=50, verbose_name='Rythme hebdomadaire')),
                ('level', models.CharField(choices=[('debutant', 'Débutant complet (Jamais pratiqué)'), ('intermediaire', 'Intermédiaire (1 à 3 ans de pratique)'), ('avance', 'Avancé (+3 ans de conservatoire / pratique)')], default='debutant', max_length=50, verbose_name='Niveau initial')),
                ('age_group', models.CharField(choices=[('4-7', 'Enfant (4 à 7 ans)'), ('8-14', 'Junior (8 à 14 ans)'), ('15-18', 'Adolescent (15 à 18 ans)'), ('adulte', 'Adulte (+18 ans)')], default='8-14', max_length=50, verbose_name="Tranche d'âge")),
                ('message', models.TextField(blank=True, verbose_name='Remarques, objectifs ou antécédents musicaux')),
                ('status', models.CharField(choices=[('nouveau', 'Nouveau dossier'), ('contacte', 'Candidat contacté'), ('audition', 'Audition de niveau programmée'), ('admis', 'Admis & Inscrit'), ('refuse', 'Dossier clôturé')], default='nouveau', max_length=30, verbose_name='Statut du dossier')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Candidature / Pré-inscription',
                'verbose_name_plural': 'Candidatures / Pré-inscriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('subject', models.CharField(max_length=200, verbose_name='Objet')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Traité / Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FacultyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Nom et Prénom')),
                ('title', models.CharField(max_length=120, verbose_name='Titre / Fonction académique')),
                ('instrument', models.CharField(max_length=100, verbose_name='Spécialité instrumentale')),
                ('aca_certified', models.BooleanField(default=True, verbose_name='Certifié Examinateur American Canadian Academy')),
                ('bio', models.TextField(verbose_name='Biographie et parcours')),
                ('credentials', models.CharField(max_length=250, verbose_name='Diplômes & Distinctions')),
                ('photo_url', models.CharField(blank=True, max_length=300, verbose_name='Lien ou chemin photo')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Professeur / Membre du jury',
                'verbose_name_plural': 'Corps professoral & Jury',
                'ordering': ['order', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Réponse détaillée')),
                ('category', models.CharField(default='aca', max_length=80, verbose_name='Catégorie (aca, cursus, tarifs, formats)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Ordre')),
            ],
            options={
                'verbose_name': 'Question fréquente (FAQ)',
                'verbose_name_plural': 'Foire aux questions (FAQ)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=120, verbose_name="Nom de l'apprenant ou parent")),
                ('role', models.CharField(max_length=150, verbose_name='Cursus / Grade ACA obtenu')),
                ('quote', models.TextField(verbose_name='Témoignage')),
                ('rating', models.PositiveSmallIntegerField(default=5, verbose_name='Note sur 5')),
                ('year', models.CharField(default='2025/2026', max_length=30, verbose_name='Année académique')),
            ],
            options={
                'verbose_name': 'Témoignage',
                'verbose_name_plural': 'Témoignages',
            },
        ),
    ]
